name: jjc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^8.0.0
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  loader_overlay: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/imgs/