// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWcMleunQPKrLJP-nJ673SsdETqwlaG3g',
    appId: '1:377756626541:web:4ed894d17828731eeed964',
    messagingSenderId: '377756626541',
    projectId: 'jjc---000',
    authDomain: 'jjc---000.firebaseapp.com',
    storageBucket: 'jjc---000.appspot.com',
    measurementId: 'G-FB7EYXTGS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiwi5jwgG7PsOrVYUVc8eETOs6X6h-jSg',
    appId: '1:377756626541:android:6cd639b13bff1772eed964',
    messagingSenderId: '377756626541',
    projectId: 'jjc---000',
    storageBucket: 'jjc---000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ZSM8K9hCVuDMntv_kWcaoJkJRmoy01I',
    appId: '1:377756626541:ios:7e0c6ca0e2a6750deed964',
    messagingSenderId: '377756626541',
    projectId: 'jjc---000',
    storageBucket: 'jjc---000.appspot.com',
    iosClientId: '377756626541-pbop4cclqlq6h7ibh1eiqu47naicghe1.apps.googleusercontent.com',
    iosBundleId: 'com.jiujitsuclub.jiujitsuclub',
  );
}
